spring:
  application:
    name: Testing
  datasource:
    password: password2
    username: jamil
    url: jdbc:postgresql://localhost:5432/customerDB

    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default-schema: public
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true